// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5bDyjE1lC7YOUQjjistMlIwRaS8djbM',
    appId: '1:1026907864696:web:ff1984c23825d7572ef78d',
    messagingSenderId: '1026907864696',
    projectId: 'watchdiary-fd847',
    authDomain: 'watchdiary-fd847.firebaseapp.com',
    storageBucket: 'watchdiary-fd847.appspot.com',
    measurementId: 'G-WF78V0HHS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB0suZPsEQ917AeEbi-UfrhDDUwj-YAm4',
    appId: '1:1026907864696:android:d236e0710e5177dc2ef78d',
    messagingSenderId: '1026907864696',
    projectId: 'watchdiary-fd847',
    storageBucket: 'watchdiary-fd847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9e0QkHLF-jgUp69Dy_DTq_fTEDsi7AW4',
    appId: '1:1026907864696:ios:83734bd4a2eb51af2ef78d',
    messagingSenderId: '1026907864696',
    projectId: 'watchdiary-fd847',
    storageBucket: 'watchdiary-fd847.appspot.com',
    iosBundleId: 'com.example.watchdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9e0QkHLF-jgUp69Dy_DTq_fTEDsi7AW4',
    appId: '1:1026907864696:ios:83734bd4a2eb51af2ef78d',
    messagingSenderId: '1026907864696',
    projectId: 'watchdiary-fd847',
    storageBucket: 'watchdiary-fd847.appspot.com',
    iosBundleId: 'com.example.watchdiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY5bDyjE1lC7YOUQjjistMlIwRaS8djbM',
    appId: '1:1026907864696:web:897f4146fb6808fa2ef78d',
    messagingSenderId: '1026907864696',
    projectId: 'watchdiary-fd847',
    authDomain: 'watchdiary-fd847.firebaseapp.com',
    storageBucket: 'watchdiary-fd847.appspot.com',
    measurementId: 'G-B3S1KJHYEJ',
  );
}
