// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA510TDKk-U-SRQImBIm_mrbTOYMpUrL_Y',
    appId: '1:950043804034:web:da38fb09fe46fe5af94f9b',
    messagingSenderId: '950043804034',
    projectId: 'watchdiary-f5441',
    authDomain: 'watchdiary-f5441.firebaseapp.com',
    storageBucket: 'watchdiary-f5441.appspot.com',
    measurementId: 'G-QTWCK387V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdOG63-_UQPaZvW34PXISpj8GS5hxCj3g',
    appId: '1:950043804034:android:51db5427c320bfc2f94f9b',
    messagingSenderId: '950043804034',
    projectId: 'watchdiary-f5441',
    storageBucket: 'watchdiary-f5441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIyDdrj_9-EYpv9cski2MSR9jgTDDqGo',
    appId: '1:950043804034:ios:3de69e4bcd671654f94f9b',
    messagingSenderId: '950043804034',
    projectId: 'watchdiary-f5441',
    storageBucket: 'watchdiary-f5441.appspot.com',
    iosClientId: '950043804034-m36kdoj4730r50c7ta1mkoml067rmf3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIyDdrj_9-EYpv9cski2MSR9jgTDDqGo',
    appId: '1:950043804034:ios:3de69e4bcd671654f94f9b',
    messagingSenderId: '950043804034',
    projectId: 'watchdiary-f5441',
    storageBucket: 'watchdiary-f5441.appspot.com',
    iosClientId: '950043804034-m36kdoj4730r50c7ta1mkoml067rmf3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchdiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA510TDKk-U-SRQImBIm_mrbTOYMpUrL_Y',
    appId: '1:950043804034:web:eef2e93aa7f05164f94f9b',
    messagingSenderId: '950043804034',
    projectId: 'watchdiary-f5441',
    authDomain: 'watchdiary-f5441.firebaseapp.com',
    storageBucket: 'watchdiary-f5441.appspot.com',
    measurementId: 'G-7X12TRYWRM',
  );

}